[package]
name = "showtimes-models"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Library for GraphQL definitions of Showtimes API"

[dependencies]
