[package]
name = "showtimes-migrate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A tools to migrate Showtimes database models and more"

[dependencies]
