[package]
name = "showtimes-webhooks"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "Webhooks delivery for Showtimes API"

[dependencies]
